"""Tracks which settings were declared in the .env file.

The config table in SQLite outranks everything else at read time, so a value that
an operator pins in .env silently loses to a stale row seeded on a previous
deploy. Recording the names that .env itself declares lets Config treat exactly
those keys as authoritative while the table keeps working for everything else.

Only names coming from the file count. Values the process happens to inherit (the
image's own ENV, a shell export) are not a deployment's declared intent and must
not take over settings the admin UI owns.

Depends on nothing but the stdlib so it stays importable from models/ and testable
without booting the application.
"""

from __future__ import annotations

import re
from pathlib import Path

_LINE = re.compile(r'^\s*(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=(.*)$')
_UNQUOTED_COMMENT = re.compile(r'\s+#')

_declared: set[str] = set()


def unquote(value: str) -> str:
    """Strip the shell-style quoting a dotenv value carries.

    `docker run --env-file` keeps surrounding quotes inside the value while
    python-dotenv and docker compose remove them, so the same .env yields
    different settings depending on how the container was started. Values are
    normalised on read instead of forcing one quoting style on the file.
    """
    value = value.strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in ('"', "'"):
        return value[1:-1]
    return _UNQUOTED_COMMENT.split(value, maxsplit=1)[0].strip()


def parse_env_file(text: str) -> dict[str, str]:
    """Parse dotenv-style text into {name: value}.

    A name counts as declared even when assigned an empty value, because
    `KEY=` is an explicit statement that the setting is empty. Later lines win,
    matching dotenv.
    """
    values: dict[str, str] = {}
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith('#'):
            continue
        match = _LINE.match(line)
        if match:
            values[match.group(1)] = unquote(match.group(2))
    return values


def parse_env_names(text: str) -> set[str]:
    """Return the variable names a dotenv-style file declares."""
    return set(parse_env_file(text))


def record_declared(names: set[str]) -> None:
    """Remember the names read from .env. Called once, from env.py, at import."""
    _declared.update(names)


def declared_names() -> frozenset[str]:
    return frozenset(_declared)


def reset_declared() -> None:
    """Drop the recorded names. For tests."""
    _declared.clear()


def env_name_for(key: str) -> str:
    """The .env name a dotted config key is configured by.

    `rag.embedding_batch_size` -> `RAG_EMBEDDING_BATCH_SIZE`, which is the name
    config.py reads to build the key's default.

    For the many keys whose default is read from a legacy-named variable,
    ENV_NAME_ALIASES maps the derived name to the one config.py actually reads
    (`web.search.enable` -> ENABLE_WEB_SEARCH, not WEB_SEARCH_ENABLE). Without the
    alias the name a deployment declares in .env never matches, env_bound() stays
    False and a stale SQLite row silently wins.
    """
    return ENV_NAME_ALIASES.get(key.upper().replace('.', '_'), key.upper().replace('.', '_'))


# Derived env names whose DEFAULT_CONFIG default is read from a differently named
# variable. Generated from config.py by the golden test in test_env_config.py, so
# the table tracks the source instead of drifting. Keys built from several env vars
# or from none at all are intentionally absent, meaning "use the derived name".
ENV_NAME_ALIASES: dict[str, str] = {
    'AUDIO_STT_DEEPGRAM_API_KEY': 'DEEPGRAM_API_KEY',
    'AUDIO_STT_WHISPER_MODEL': 'WHISPER_MODEL',
    'AUTH_ADMIN_EMAIL': 'ADMIN_EMAIL',
    'AUTH_ADMIN_SHOW': 'SHOW_ADMIN_DETAILS',
    'AUTH_ENABLE_API_KEYS': 'ENABLE_API_KEYS',
    'AUTH_JWT_EXPIRY': 'JWT_EXPIRES_IN',
    'AUTOMATIONS_AUTH_TOKEN_EXPIRES_IN': 'AUTOMATION_AUTH_TOKEN_EXPIRES_IN',
    'AUTOMATIONS_ENABLE': 'ENABLE_AUTOMATIONS',
    'AUTOMATIONS_MAX_COUNT': 'AUTOMATION_MAX_COUNT',
    'AUTOMATIONS_MIN_INTERVAL': 'AUTOMATION_MIN_INTERVAL',
    'CALENDAR_ENABLE': 'ENABLE_CALENDAR',
    'CHANNELS_ENABLE': 'ENABLE_CHANNELS',
    'CHAT_CONTEXT_COMPACTION_ENABLE': 'ENABLE_CONTEXT_COMPACTION',
    'CHAT_CONTEXT_COMPACTION_PROMPT_TEMPLATE': 'CONTEXT_COMPACTION_PROMPT_TEMPLATE',
    'CHAT_CONTEXT_COMPACTION_TOKEN_THRESHOLD': 'CONTEXT_COMPACTION_TOKEN_THRESHOLD',
    'CODE_EXECUTION_ENABLE': 'ENABLE_CODE_EXECUTION',
    'CODE_INTERPRETER_ENABLE': 'ENABLE_CODE_INTERPRETER',
    'DIRECT_ENABLE': 'ENABLE_DIRECT_CONNECTIONS',
    'EVALUATION_ARENA_ENABLE': 'ENABLE_EVALUATION_ARENA_MODELS',
    'FOLDERS_ENABLE': 'ENABLE_FOLDERS',
    'FOLDERS_MAX_FILE_COUNT': 'FOLDER_MAX_FILE_COUNT',
    'GOOGLE_DRIVE_ENABLE': 'ENABLE_GOOGLE_DRIVE_INTEGRATION',
    'IMAGES_EDIT_COMFYUI_NODES': 'IMAGES_EDIT_COMFYUI_WORKFLOW_NODES',
    'IMAGES_EDIT_ENABLE': 'ENABLE_IMAGE_EDIT',
    'IMAGES_EDIT_ENGINE': 'IMAGE_EDIT_ENGINE',
    'IMAGES_EDIT_MODEL': 'IMAGE_EDIT_MODEL',
    'IMAGES_EDIT_SIZE': 'IMAGE_EDIT_SIZE',
    'IMAGE_GENERATION_AUTOMATIC1111_API_AUTH': 'AUTOMATIC1111_API_AUTH',
    'IMAGE_GENERATION_AUTOMATIC1111_API_PARAMS': 'AUTOMATIC1111_PARAMS',
    'IMAGE_GENERATION_AUTOMATIC1111_BASE_URL': 'AUTOMATIC1111_BASE_URL',
    'IMAGE_GENERATION_COMFYUI_API_KEY': 'COMFYUI_API_KEY',
    'IMAGE_GENERATION_COMFYUI_BASE_URL': 'COMFYUI_BASE_URL',
    'IMAGE_GENERATION_COMFYUI_NODES': 'COMFYUI_WORKFLOW_NODES',
    'IMAGE_GENERATION_COMFYUI_WORKFLOW': 'COMFYUI_WORKFLOW',
    'IMAGE_GENERATION_ENABLE': 'ENABLE_IMAGE_GENERATION',
    'IMAGE_GENERATION_GEMINI_API_BASE_URL': 'IMAGES_GEMINI_API_BASE_URL',
    'IMAGE_GENERATION_GEMINI_API_KEY': 'IMAGES_GEMINI_API_KEY',
    'IMAGE_GENERATION_GEMINI_ENDPOINT_METHOD': 'IMAGES_GEMINI_ENDPOINT_METHOD',
    'IMAGE_GENERATION_OPENAI_API_BASE_URL': 'IMAGES_OPENAI_API_BASE_URL',
    'IMAGE_GENERATION_OPENAI_API_KEY': 'IMAGES_OPENAI_API_KEY',
    'IMAGE_GENERATION_OPENAI_API_VERSION': 'IMAGES_OPENAI_API_VERSION',
    'IMAGE_GENERATION_OPENAI_PARAMS': 'IMAGES_OPENAI_PARAMS',
    'IMAGE_GENERATION_PROMPT_ENABLE': 'ENABLE_IMAGE_PROMPT_GENERATION',
    'IMAGE_GENERATION_SIZE': 'IMAGE_SIZE',
    'IMAGE_GENERATION_STEPS': 'IMAGE_STEPS',
    'LDAP_ENABLE': 'ENABLE_LDAP',
    'LDAP_GROUP_ENABLE_CREATION': 'ENABLE_LDAP_GROUP_CREATION',
    'LDAP_GROUP_ENABLE_MANAGEMENT': 'ENABLE_LDAP_GROUP_MANAGEMENT',
    'LDAP_SERVER_APP_DN': 'LDAP_APP_DN',
    'LDAP_SERVER_APP_PASSWORD': 'LDAP_APP_PASSWORD',
    'LDAP_SERVER_ATTRIBUTE_FOR_GROUPS': 'LDAP_ATTRIBUTE_FOR_GROUPS',
    'LDAP_SERVER_ATTRIBUTE_FOR_MAIL': 'LDAP_ATTRIBUTE_FOR_MAIL',
    'LDAP_SERVER_ATTRIBUTE_FOR_USERNAME': 'LDAP_ATTRIBUTE_FOR_USERNAME',
    'LDAP_SERVER_CA_CERT_FILE': 'LDAP_CA_CERT_FILE',
    'LDAP_SERVER_CIPHERS': 'LDAP_CIPHERS',
    'LDAP_SERVER_USERS_DN': 'LDAP_SEARCH_BASE',
    'LDAP_SERVER_USE_TLS': 'LDAP_USE_TLS',
    'LDAP_SERVER_VALIDATE_CERT': 'LDAP_VALIDATE_CERT',
    'MEMORIES_BACKGROUND_REVIEW_ENABLE': 'ENABLE_MEMORY_BACKGROUND_REVIEW',
    'MEMORIES_ENABLE': 'ENABLE_MEMORIES',
    'MEMORIES_SYSTEM_CONTEXT_ENABLE': 'ENABLE_MEMORY_SYSTEM_CONTEXT',
    'MODELS_BASE_MODELS_CACHE': 'ENABLE_BASE_MODELS_CACHE',
    'MODELS_DEFAULT_METADATA': 'DEFAULT_MODEL_METADATA',
    'MODELS_DEFAULT_PARAMS': 'DEFAULT_MODEL_PARAMS',
    'NOTES_ENABLE': 'ENABLE_NOTES',
    'OAUTH_ENABLE_GROUP_CREATION': 'ENABLE_OAUTH_GROUP_CREATION',
    'OAUTH_ENABLE_GROUP_MAPPING': 'ENABLE_OAUTH_GROUP_MANAGEMENT',
    'OAUTH_ENABLE_ROLE_MAPPING': 'ENABLE_OAUTH_ROLE_MANAGEMENT',
    'OAUTH_ENABLE_SIGNUP': 'ENABLE_OAUTH_SIGNUP',
    'OAUTH_END_SESSION_ENDPOINT': 'OPENID_END_SESSION_ENDPOINT',
    'OAUTH_FEISHU_CLIENT_ID': 'FEISHU_CLIENT_ID',
    'OAUTH_FEISHU_CLIENT_SECRET': 'FEISHU_CLIENT_SECRET',
    'OAUTH_FEISHU_REDIRECT_URI': 'FEISHU_REDIRECT_URI',
    'OAUTH_FEISHU_SCOPE': 'FEISHU_OAUTH_SCOPE',
    'OAUTH_GITHUB_CLIENT_ID': 'GITHUB_CLIENT_ID',
    'OAUTH_GITHUB_CLIENT_SECRET': 'GITHUB_CLIENT_SECRET',
    'OAUTH_GITHUB_REDIRECT_URI': 'GITHUB_CLIENT_REDIRECT_URI',
    'OAUTH_GITHUB_SCOPE': 'GITHUB_CLIENT_SCOPE',
    'OAUTH_GOOGLE_CLIENT_ID': 'GOOGLE_CLIENT_ID',
    'OAUTH_GOOGLE_CLIENT_SECRET': 'GOOGLE_CLIENT_SECRET',
    'OAUTH_GOOGLE_REDIRECT_URI': 'GOOGLE_REDIRECT_URI',
    'OAUTH_GOOGLE_SCOPE': 'GOOGLE_OAUTH_SCOPE',
    'OAUTH_MICROSOFT_CLIENT_ID': 'MICROSOFT_CLIENT_ID',
    'OAUTH_MICROSOFT_CLIENT_SECRET': 'MICROSOFT_CLIENT_SECRET',
    'OAUTH_MICROSOFT_LOGIN_BASE_URL': 'MICROSOFT_CLIENT_LOGIN_BASE_URL',
    'OAUTH_MICROSOFT_PICTURE_URL': 'MICROSOFT_CLIENT_PICTURE_URL',
    'OAUTH_MICROSOFT_REDIRECT_URI': 'MICROSOFT_REDIRECT_URI',
    'OAUTH_MICROSOFT_SCOPE': 'MICROSOFT_OAUTH_SCOPE',
    'OAUTH_MICROSOFT_TENANT_ID': 'MICROSOFT_CLIENT_TENANT_ID',
    'OAUTH_PROVIDER_URL': 'OPENID_PROVIDER_URL',
    'OAUTH_REDIRECT_URI': 'OPENID_REDIRECT_URI',
    'OLLAMA_ENABLE': 'ENABLE_OLLAMA_API',
    'ONEDRIVE_ENABLE': 'ENABLE_ONEDRIVE_INTEGRATION',
    'OPENAI_ENABLE': 'ENABLE_OPENAI_API',
    'RAG_BYPASS_EMBEDDING_AND_RETRIEVAL': 'BYPASS_EMBEDDING_AND_RETRIEVAL',
    'RAG_CONTENT_EXTRACTION_ENGINE': 'CONTENT_EXTRACTION_ENGINE',
    'RAG_DATALAB_MARKER_ADDITIONAL_CONFIG': 'DATALAB_MARKER_ADDITIONAL_CONFIG',
    'RAG_DATALAB_MARKER_API_BASE_URL': 'DATALAB_MARKER_API_BASE_URL',
    'RAG_DATALAB_MARKER_API_KEY': 'DATALAB_MARKER_API_KEY',
    'RAG_DATALAB_MARKER_DISABLE_IMAGE_EXTRACTION': 'DATALAB_MARKER_DISABLE_IMAGE_EXTRACTION',
    'RAG_DATALAB_MARKER_FORCE_OCR': 'DATALAB_MARKER_FORCE_OCR',
    'RAG_DATALAB_MARKER_FORMAT_LINES': 'DATALAB_MARKER_FORMAT_LINES',
    'RAG_DATALAB_MARKER_OUTPUT_FORMAT': 'DATALAB_MARKER_OUTPUT_FORMAT',
    'RAG_DATALAB_MARKER_PAGINATE': 'DATALAB_MARKER_PAGINATE',
    'RAG_DATALAB_MARKER_SKIP_CACHE': 'DATALAB_MARKER_SKIP_CACHE',
    'RAG_DATALAB_MARKER_STRIP_EXISTING_OCR': 'DATALAB_MARKER_STRIP_EXISTING_OCR',
    'RAG_DATALAB_MARKER_USE_LLM': 'DATALAB_MARKER_USE_LLM',
    'RAG_DOCLING_API_KEY': 'DOCLING_API_KEY',
    'RAG_DOCLING_PARAMS': 'DOCLING_PARAMS',
    'RAG_DOCLING_SERVER_URL': 'DOCLING_SERVER_URL',
    'RAG_DOCUMENT_INTELLIGENCE_ENDPOINT': 'DOCUMENT_INTELLIGENCE_ENDPOINT',
    'RAG_DOCUMENT_INTELLIGENCE_KEY': 'DOCUMENT_INTELLIGENCE_KEY',
    'RAG_DOCUMENT_INTELLIGENCE_MODEL': 'DOCUMENT_INTELLIGENCE_MODEL',
    'RAG_ENABLE_ASYNC_EMBEDDING': 'ENABLE_ASYNC_EMBEDDING',
    'RAG_ENABLE_HYBRID_SEARCH': 'ENABLE_RAG_HYBRID_SEARCH',
    'RAG_ENABLE_HYBRID_SEARCH_ENRICHED_TEXTS': 'ENABLE_RAG_HYBRID_SEARCH_ENRICHED_TEXTS',
    'RAG_ENABLE_MARKDOWN_HEADER_TEXT_SPLITTER': 'ENABLE_MARKDOWN_HEADER_TEXT_SPLITTER',
    'RAG_EXTERNAL_DOCUMENT_LOADER_API_KEY': 'EXTERNAL_DOCUMENT_LOADER_API_KEY',
    'RAG_EXTERNAL_DOCUMENT_LOADER_HEADERS': 'EXTERNAL_DOCUMENT_LOADER_HEADERS',
    'RAG_EXTERNAL_DOCUMENT_LOADER_URL': 'EXTERNAL_DOCUMENT_LOADER_URL',
    'RAG_FILE_ALLOWED_EXTENSIONS': 'RAG_ALLOWED_FILE_EXTENSIONS',
    'RAG_MINERU_API_KEY': 'MINERU_API_KEY',
    'RAG_MINERU_API_MODE': 'MINERU_API_MODE',
    'RAG_MINERU_API_TIMEOUT': 'MINERU_API_TIMEOUT',
    'RAG_MINERU_API_URL': 'MINERU_API_URL',
    'RAG_MINERU_FILE_EXTENSIONS': 'MINERU_FILE_EXTENSIONS',
    'RAG_MINERU_PARAMS': 'MINERU_PARAMS',
    'RAG_MISTRAL_OCR_API_BASE_URL': 'MISTRAL_OCR_API_BASE_URL',
    'RAG_MISTRAL_OCR_API_KEY': 'MISTRAL_OCR_API_KEY',
    'RAG_MISTRAL_OCR_USE_BASE64': 'MISTRAL_OCR_USE_BASE64',
    'RAG_PADDLEOCR_VL_BASE_URL': 'PADDLEOCR_VL_BASE_URL',
    'RAG_PADDLEOCR_VL_TOKEN': 'PADDLEOCR_VL_TOKEN',
    'RAG_PDF_EXTRACT_IMAGES': 'PDF_EXTRACT_IMAGES',
    'RAG_PDF_LOADER_MODE': 'PDF_LOADER_MODE',
    'RAG_TIKA_SERVER_URL': 'TIKA_SERVER_URL',
    'RAG_TIKTOKEN_ENCODING_NAME': 'TIKTOKEN_ENCODING_NAME',
    'RAG_YOUTUBE_LOADER_LANGUAGE': 'YOUTUBE_LOADER_LANGUAGE',
    'RAG_YOUTUBE_LOADER_PROXY_URL': 'YOUTUBE_LOADER_PROXY_URL',
    'TASK_AUTOCOMPLETE_ENABLE': 'ENABLE_AUTOCOMPLETE_GENERATION',
    'TASK_AUTOCOMPLETE_INPUT_MAX_LENGTH': 'AUTOCOMPLETE_GENERATION_INPUT_MAX_LENGTH',
    'TASK_AUTOCOMPLETE_PROMPT_TEMPLATE': 'AUTOCOMPLETE_GENERATION_PROMPT_TEMPLATE',
    'TASK_FOLLOW_UP_ENABLE': 'ENABLE_FOLLOW_UP_GENERATION',
    'TASK_FOLLOW_UP_PROMPT_TEMPLATE': 'FOLLOW_UP_GENERATION_PROMPT_TEMPLATE',
    'TASK_IMAGE_PROMPT_TEMPLATE': 'IMAGE_PROMPT_GENERATION_PROMPT_TEMPLATE',
    'TASK_MODEL_DEFAULT': 'TASK_MODEL',
    'TASK_QUERY_PROMPT_TEMPLATE': 'QUERY_GENERATION_PROMPT_TEMPLATE',
    'TASK_QUERY_RETRIEVAL_ENABLE': 'ENABLE_RETRIEVAL_QUERY_GENERATION',
    'TASK_QUERY_SEARCH_ENABLE': 'ENABLE_SEARCH_QUERY_GENERATION',
    'TASK_TAGS_ENABLE': 'ENABLE_TAGS_GENERATION',
    'TASK_TAGS_PROMPT_TEMPLATE': 'TAGS_GENERATION_PROMPT_TEMPLATE',
    'TASK_TITLE_ENABLE': 'ENABLE_TITLE_GENERATION',
    'TASK_TITLE_PROMPT_TEMPLATE': 'TITLE_GENERATION_PROMPT_TEMPLATE',
    'TASK_TOOLS_PROMPT_TEMPLATE': 'TOOLS_FUNCTION_CALLING_PROMPT_TEMPLATE',
    'TASK_VOICE_PROMPT_ENABLE': 'ENABLE_VOICE_MODE_PROMPT',
    'TASK_VOICE_PROMPT_TEMPLATE': 'VOICE_MODE_PROMPT_TEMPLATE',
    'UI_BANNERS': 'WEBUI_BANNERS',
    'UI_DEFAULT_GROUP_ID': 'DEFAULT_GROUP_ID',
    'UI_DEFAULT_LOCALE': 'DEFAULT_LOCALE',
    'UI_DEFAULT_MODELS': 'DEFAULT_MODELS',
    'UI_DEFAULT_PINNED_MODELS': 'DEFAULT_PINNED_MODELS',
    'UI_DEFAULT_USER_ROLE': 'DEFAULT_USER_ROLE',
    'UI_ENABLE_COMMUNITY_SHARING': 'ENABLE_COMMUNITY_SHARING',
    'UI_ENABLE_LOGIN_FORM': 'ENABLE_LOGIN_FORM',
    'UI_ENABLE_MESSAGE_RATING': 'ENABLE_MESSAGE_RATING',
    'UI_ENABLE_PASSWORD_CHANGE_FORM': 'ENABLE_PASSWORD_CHANGE_FORM',
    'UI_ENABLE_SIGNUP': 'ENABLE_SIGNUP',
    'UI_ENABLE_USER_WEBHOOKS': 'ENABLE_USER_WEBHOOKS',
    'UI_PENDING_USER_OVERLAY_CONTENT': 'PENDING_USER_OVERLAY_CONTENT',
    'UI_PENDING_USER_OVERLAY_TITLE': 'PENDING_USER_OVERLAY_TITLE',
    'UI_PROMPT_SUGGESTIONS': 'DEFAULT_PROMPT_SUGGESTIONS',
    'UI_WATERMARK': 'RESPONSE_WATERMARK',
    'USERS_ENABLE_STATUS': 'ENABLE_USER_STATUS',
    'WEB_LOADER_EXTERNAL_WEB_LOADER_API_KEY': 'EXTERNAL_WEB_LOADER_API_KEY',
    'WEB_LOADER_EXTERNAL_WEB_LOADER_URL': 'EXTERNAL_WEB_LOADER_URL',
    'WEB_LOADER_FIRECRAWL_API_KEY': 'FIRECRAWL_API_KEY',
    'WEB_LOADER_FIRECRAWL_API_URL': 'FIRECRAWL_API_BASE_URL',
    'WEB_LOADER_FIRECRAWL_TIMEOUT': 'FIRECRAWL_TIMEOUT',
    'WEB_LOADER_PLAYWRIGHT_TIMEOUT': 'PLAYWRIGHT_TIMEOUT',
    'WEB_LOADER_PLAYWRIGHT_WS_URL': 'PLAYWRIGHT_WS_URL',
    'WEB_LOADER_SSL_VERIFICATION': 'ENABLE_WEB_LOADER_SSL_VERIFICATION',
    'WEB_SEARCH_AZURE_AI_SEARCH_API_KEY': 'AZURE_AI_SEARCH_API_KEY',
    'WEB_SEARCH_AZURE_AI_SEARCH_ENDPOINT': 'AZURE_AI_SEARCH_ENDPOINT',
    'WEB_SEARCH_AZURE_AI_SEARCH_INDEX_NAME': 'AZURE_AI_SEARCH_INDEX_NAME',
    'WEB_SEARCH_BING_SEARCH_V7_ENDPOINT': 'BING_SEARCH_V7_ENDPOINT',
    'WEB_SEARCH_BING_SEARCH_V7_SUBSCRIPTION_KEY': 'BING_SEARCH_V7_SUBSCRIPTION_KEY',
    'WEB_SEARCH_BOCHA_SEARCH_API_KEY': 'BOCHA_SEARCH_API_KEY',
    'WEB_SEARCH_BRAVE_SEARCH_API_KEY': 'BRAVE_SEARCH_API_KEY',
    'WEB_SEARCH_BRAVE_SEARCH_CONTEXT_TOKENS': 'BRAVE_SEARCH_CONTEXT_TOKENS',
    'WEB_SEARCH_BYPASS_EMBEDDING_AND_RETRIEVAL': 'BYPASS_WEB_SEARCH_EMBEDDING_AND_RETRIEVAL',
    'WEB_SEARCH_BYPASS_WEB_LOADER': 'BYPASS_WEB_SEARCH_WEB_LOADER',
    'WEB_SEARCH_CONFIRMATION_ENABLE': 'ENABLE_WEB_SEARCH_CONFIRMATION',
    'WEB_SEARCH_DDGS_BACKEND': 'DDGS_BACKEND',
    'WEB_SEARCH_ENABLE': 'ENABLE_WEB_SEARCH',
    'WEB_SEARCH_EXA_API_KEY': 'EXA_API_KEY',
    'WEB_SEARCH_EXTERNAL_WEB_SEARCH_API_KEY': 'EXTERNAL_WEB_SEARCH_API_KEY',
    'WEB_SEARCH_EXTERNAL_WEB_SEARCH_URL': 'EXTERNAL_WEB_SEARCH_URL',
    'WEB_SEARCH_GOOGLE_PSE_API_KEY': 'GOOGLE_PSE_API_KEY',
    'WEB_SEARCH_GOOGLE_PSE_ENGINE_ID': 'GOOGLE_PSE_ENGINE_ID',
    'WEB_SEARCH_JINA_API_BASE_URL': 'JINA_API_BASE_URL',
    'WEB_SEARCH_JINA_API_KEY': 'JINA_API_KEY',
    'WEB_SEARCH_KAGI_SEARCH_API_KEY': 'KAGI_SEARCH_API_KEY',
    'WEB_SEARCH_LINKUP_API_KEY': 'LINKUP_API_KEY',
    'WEB_SEARCH_LINKUP_SEARCH_PARAMS': 'LINKUP_SEARCH_PARAMS',
    'WEB_SEARCH_MICROSOFT_WEB_IQ_API_BASE_URL': 'MICROSOFT_WEB_IQ_API_BASE_URL',
    'WEB_SEARCH_MICROSOFT_WEB_IQ_API_KEY': 'MICROSOFT_WEB_IQ_API_KEY',
    'WEB_SEARCH_MICROSOFT_WEB_IQ_LANGUAGE': 'MICROSOFT_WEB_IQ_LANGUAGE',
    'WEB_SEARCH_MOJEEK_SEARCH_API_KEY': 'MOJEEK_SEARCH_API_KEY',
    'WEB_SEARCH_OLLAMA_CLOUD_API_KEY': 'OLLAMA_CLOUD_API_KEY',
    'WEB_SEARCH_PERPLEXITY_API_KEY': 'PERPLEXITY_API_KEY',
    'WEB_SEARCH_PERPLEXITY_MODEL': 'PERPLEXITY_MODEL',
    'WEB_SEARCH_PERPLEXITY_SEARCH_API_URL': 'PERPLEXITY_SEARCH_API_URL',
    'WEB_SEARCH_PERPLEXITY_SEARCH_CONTEXT_USAGE': 'PERPLEXITY_SEARCH_CONTEXT_USAGE',
    'WEB_SEARCH_SEARCHAPI_API_KEY': 'SEARCHAPI_API_KEY',
    'WEB_SEARCH_SEARCHAPI_ENGINE': 'SEARCHAPI_ENGINE',
    'WEB_SEARCH_SEARXNG_LANGUAGE': 'SEARXNG_LANGUAGE',
    'WEB_SEARCH_SEARXNG_QUERY_URL': 'SEARXNG_QUERY_URL',
    'WEB_SEARCH_SERPAPI_API_KEY': 'SERPAPI_API_KEY',
    'WEB_SEARCH_SERPAPI_ENGINE': 'SERPAPI_ENGINE',
    'WEB_SEARCH_SERPER_API_KEY': 'SERPER_API_KEY',
    'WEB_SEARCH_SERPHOUSE_API_KEY': 'SERPHOUSE_API_KEY',
    'WEB_SEARCH_SERPHOUSE_DOMAIN': 'SERPHOUSE_DOMAIN',
    'WEB_SEARCH_SERPLY_API_KEY': 'SERPLY_API_KEY',
    'WEB_SEARCH_SERPSTACK_API_KEY': 'SERPSTACK_API_KEY',
    'WEB_SEARCH_SERPSTACK_HTTPS': 'SERPSTACK_HTTPS',
    'WEB_SEARCH_SOUGOU_API_SID': 'SOUGOU_API_SID',
    'WEB_SEARCH_SOUGOU_API_SK': 'SOUGOU_API_SK',
    'WEB_SEARCH_TAVILY_API_KEY': 'TAVILY_API_KEY',
    'WEB_SEARCH_TAVILY_EXTRACT_DEPTH': 'TAVILY_EXTRACT_DEPTH',
    'WEB_SEARCH_YACY_PASSWORD': 'YACY_PASSWORD',
    'WEB_SEARCH_YACY_QUERY_URL': 'YACY_QUERY_URL',
    'WEB_SEARCH_YACY_USERNAME': 'YACY_USERNAME',
    'WEB_SEARCH_YANDEX_WEB_SEARCH_API_KEY': 'YANDEX_WEB_SEARCH_API_KEY',
    'WEB_SEARCH_YANDEX_WEB_SEARCH_CONFIG': 'YANDEX_WEB_SEARCH_CONFIG',
    'WEB_SEARCH_YANDEX_WEB_SEARCH_URL': 'YANDEX_WEB_SEARCH_URL',
}


def is_declared_in_env(key: str) -> bool:
    """True when .env pins this config key, so .env outranks the stored row."""
    return env_name_for(key) in _declared


def read_env_file(path: Path) -> set[str]:
    """Parse a .env file if present and record its names. Returns what was found."""
    try:
        text = path.read_text(encoding='utf-8')
    except OSError:
        return set()
    names = parse_env_names(text)
    record_declared(names)
    return names
